display_name: Code Clip
package_name: codeclip

maintainer:
  name: Hosein Dehghan
  email: hoseda97@gmail.com

priority: optional

section: x11

installed_size: 55000

dependencies:
  - libgtk-3-0
  - libblkid1
  - liblzma5
  - libc6
  - libstdc++6
  - libsqlite3-0
  - libglib2.0-0
  - libpango-1.0-0
  - libpangocairo-1.0-0
  - libgdk-pixbuf2.0-0
  - libcairo2
  - libatk1.0-0
  - libx11-6
  - libxext6
  - libxinerama1
  - libxrandr2
  - libxcursor1
  - libxcomposite1
  - libxdamage1
  - libwayland-client0
  - libwayland-cursor0
  - libwayland-egl1
  - libxkbcommon0
  

essential: false

icon: linux/assets/icon.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - Snippet
  - Code Clip

generic_name: Code Clip

categories:
  - Development
  - Utility

startup_notify: true